### ISSUE TITLE
OCaml 5.2 support

### ISSUE THREAD

**Issue by kit-ty-kate** [rescript-association/reanalyze#196]
The current release of reanalyze does not compile with OCaml 5.2 and fails with:
```
File "src/Log_.ml", line 57, characters 39-58:
Error: Unbound value CL.Misc.Color.setup
```

**Comment by kit-ty-kate** [comment]
Update: beta1 got released today

**Comment by cknitt** [comment]
@kit-ty-kate I tried to publish to opam, but there seems to be an issue with opam CI: https://github.com/ocaml/opam-repository/pull/25941

**Comment by kit-ty-kate** [comment]
@cknitt this is being tracked in https://github.com/ocaml/opam/issues/5971 but for now we're not sure if it's an issue on their cluster so we can't do much. In any case these errors are being ignored by opam-repository maintainers so it shouldn't cause any problem for your PR.

Thanks for doing this!
